export const FETCHING_COINS = 'FETCHING_COINS';
export const FETCHING_COINS_SUCCESS = 'FETCHING_COINS_SUCCESS';
export const FETCHING_COINS_FAIL = 'FETCHING_COINS_FAIL';
export const CHANGE_VALUE_BASE = 'CHANGE_VALUE_BASE';